name: Deploy

on:
  push:
    branches:
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        run: |
          ssh user@staging-server "cd /var/www/staging && git pull && php artisan migrate --force"

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          ssh user@production-server "cd /var/www/production && git pull && php artisan migrate --force"


          
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
            docker build -t your-dockerhub-username/laravel-backend:${{ github.sha }} .
            docker push your-dockerhub-username/laravel-backend:${{ github.sha }}